# Generated by Django 4.0.5 on 2022-07-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='', upload_to='cadd/images'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(default='', upload_to='cadd/images'),
        ),
    ]
